---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-qbittorrent
spec:
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    path: /mnt/config/qbittorrent
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lima-k3s
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-qbittorrent
spec:
  volumeMode: Filesystem
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    path: /mnt/media/downloads
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lima-k3s