---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flaresolverr
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flaresolverr
    spec:
      containers:
      - image: flaresolverr/flaresolverr
        imagePullPolicy: Always
        name: flaresolverr
        ports:
        - containerPort: 8191
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
spec:
  ports:
    - port: 8191
      targetPort: 8191
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/name: flaresolverr