---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qbittorrent
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: claim-config-qbittorrent
        - name: media
          persistentVolumeClaim:
            claimName: claim-media-qbittorrent
      containers:
      - image: linuxserver/qbittorrent
        imagePullPolicy: IfNotPresent
        name: qbittorrent
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /downloads
            name: media
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/name: qbittorrent
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-config-qbittorrent
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: config-qbittorrent
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-media-qbittorrent
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: media-qbittorrent